### ISSUE TITLE
utils.isThisANonHTMLUrl causing false positives on domains that start with invalid image type strings

### ISSUE THREAD

**Issue by steve1000** [jshemas/openGraphScraper#107]
For example: `https://www.target.com.au/path-to-product` will fail as `.tar` is one of the invalid image types. This causes the `Must scrape an HTML page` error.

Looking at the code I assume this will happen for any URL that has any of the invalid images types in its domain whether it be domain or sub-domain. E.g. `https://products.txtshop.com/product`

If I get a spare few mins I'll submit a PR with some sort of solution.

Just thought I'd make you aware of the issue :)

Update: PR submitted: https://github.com/jshemas/openGraphScraper/pull/108

Steve

**Comment by jshemas** [comment]
Great catch!!! Thank you for the PR, your changes are live in `open-graph-scraper@4.6.0`.
