### ISSUE TITLE
Twitter doesn't response image etc

### ISSUE THREAD

**Issue by shingom** [jshemas/openGraphScraper#113]
It cause of this.
They response this page.
<img width="584" alt="Screen Shot 2020-12-07 at 18 17 42" src="https://user-images.githubusercontent.com/9330478/101332591-d72b2900-38b8-11eb-9bfb-b244da5d71e9.png">

**Comment by jshemas** [comment]
Twitter does a lot of weird stuff to stop it from getting scraped. You can try setting your `user-agent` to different things like you did in your PR, but you might also run into the same as this problem: https://github.com/jshemas/openGraphScraper/issues/90
