### ISSUE TITLE
Strange fallback behavior with multiple title tags.

### ISSUE THREAD

**Issue by catnose99** [jshemas/openGraphScraper#118]
Hi. I've found multiple title tags are automatically concatenated and generate long ogTitle. I don't think this is the expected behavior. 

**example1**
Html below generates ogTitle: `foobarbaz`
```
<html><head><title>foo</title></head><body><svg><title>bar</title></svg><svg><title>baz</title></svg></body></html>
```

**example2**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
This page has many title tags inside svg tags. Fetching the page causes ogTitle to be 

`Date.prototype.toLocaleString() - JavaScript | MDNThis deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This deprecated API should no longer be used, but will probably still work.This API has not been standardized.This is an obsolete API and is no longer guaranteed to work.
`

You can check reproduction here.
https://codesandbox.io/s/quirky-wood-1z2t9?file=/package.json

This PR fixes the issue.
https://github.com/jshemas/openGraphScraper/pull/119

**Comment by jshemas** [comment]
Thanks for the PR. Fix is in `open-graph-scraper@4.8.1`
