### ISSUE TITLE
Page not found with fake user-agent and without user-agent

### ISSUE THREAD

**Issue by naxxateux** [jshemas/openGraphScraper#126]
Hi, @jshemas !

Thnx for the amazing tool!

I’ve faced a problem with this url: https://www.socialmediaexaminer.com/.

OGS returns the following:
```
Error: Page not found
    at parsePageInfo (/Users/naxxateux/sites/amplifr/amplifr-preview/controllers/parse-page-info.js:112:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Server.onRequest (/Users/naxxateux/sites/amplifr/amplifr-preview/server.js:29:18) {
  statusCode: 400,
  code: undefined
```
  
I’ve tried to delete or replace user agent according to the same issues, but it doesn’t help. Could you help me please with debugging?

**Comment by jshemas** [comment]
Hello,

It looks like the webserver is returning an `HTTPError: Response code 403 (Forbidden)` error. I'm not sure if there is a way around this but I can dig into it more.

**Comment by naxxateux** [comment]
Strange url 🤔 Thnx for your help. I would be grateful if you could help with further debugging.

**Comment by jshemas** [comment]
You can try using a `proxy` with a `user-agent` but other then that, there isn't much we can do if the website is blocking scrapers.
