### ISSUE TITLE
Angular usage. 

### ISSUE THREAD

**Issue by AidasMIT** [jshemas/openGraphScraper#127]
Hi @jshemas, thanks for the module. 
I faced an issue, I tried to use this module in angular project, however it simply brakes the app.
I used the guide to achieve this. https://angular.io/guide/using-libraries
Maybe you could provide me some details how to run this module in angular. Would be very thankful.

**Comment by jshemas** [comment]
Hello,

I'm not familiar with Angular, but if you need `@types` you can check out https://www.npmjs.com/package/@types/open-graph-scraper

Here is an example of trying to get OGS working in `vue` https://github.com/jshemas/vue-opengraph but I ran into a bunch of cors issues. You can also try using https://github.com/jshemas/openGraphScraperLite

**Comment by wobsoriano** [comment]
> Hello,
> 
> I'm not familiar with Angular, but if you need `@types` you can check out https://www.npmjs.com/package/@types/open-graph-scraper
> 
> Here is an example of trying to get OGS working in `vue` https://github.com/jshemas/vue-opengraph but I ran into a bunch of cors issues. You can also try using https://github.com/jshemas/openGraphScraperLite

It's meant to be used with reverse proxy libraries like https://github.com/Rob--W/cors-anywhere

end of the day you can't just use it in a front-end app
