### ISSUE TITLE
 open-graph-scraper doesn't return response body with the use of proxy

### ISSUE THREAD

**Issue by susampath-ceylonsolutions** [jshemas/openGraphScraper#130]
Hey,
I am using open-graph-scraper with proxies as mentioned in the documentation. It works fine with a normal start-up. As an example when I run the node program using `node server.js` it returns the result as follows.
`{
    "ogDescription": "Node.js scraper module for Open Graph and Twitter Card info",
    "ogTitle": "open-graph-scraper",
    "ogUrl": "https://www.npmjs.com/package/open-graph-scraper",
    "ogSiteName": "npm",
    "twitterCard": "summary",
    "twitterUrl": "https://www.npmjs.com/package/open-graph-scraper",
    "twitterTitle": "npm: open-graph-scraper",
    "twitterDescription": "Node.js scraper module for Open Graph and Twitter Card info",
    "ogImage": {
        "url": "https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png",
        "width": null,
        "height": null,
        "type": "png"
    },
    "ogLocale": "en",
    "ogDate": "2021-08-10T00:29:36.453Z",
    "charset": "utf8",
    "requestUrl": "https://www.npmjs.com/package/open-graph-scraper",
    "success": true
}`
But when I try to run the same program using the docker container the result looks like this. Basically, it doesn't have a response body.
`{
    "charset": null,
    "requestUrl": "https://www.npmjs.com/package/open-graph-scraper",
    "success": true
}`

This is my docker file

`
FROM node:14

FROM keymetrics/pm2:latest-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000 22 3128

CMD [ "pm2-runtime", "start", "server.js" ]
`

This is the command I used to run the docker image.
`docker run  -it --rm -p 3000:3000  <container-name>`

I would be much thankful if anyone can give a solution for this.

**Comment by jshemas** [comment]
Hello,

Can you try using `FROM keymetrics/pm2:14-alpine`? I was able to get that to work locally.

**Comment by jshemas** [comment]
Example:

dockerfile
```
FROM node:14

FROM keymetrics/pm2:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000 22 3128

CMD [ "pm2-runtime", "start", "server.js" ]
```
server.js
```
const ogs = require('open-graph-scraper');

const options = {
  url: 'http://ogp.me/',
  headers: {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36',
  }
};

ogs(options)
  .then((data) => {
    const { error, result, response } = data;
    console.log('error:', error); // This is returns true or false. True if there was a error. The error it self is inside the results object.
    console.log('result:', result); // This contains all of the Open Graph results
    console.log('response:', response); // This contains the HTML of page
  });
```

**Comment by susampath-ceylonsolutions** [comment]
Hey @jshemas ,
Thanks a lot for the reply. I worked fine when I change the docker file as you have mentioned. I used not the header option but the proxy method.

> const ogs = require('open-graph-scraper');
   const tunnel = require('tunnel');
   const options = {
        url: 'https://whatismyipaddress.com/',
       timeout: 15000,
       agent: {
    https: tunnel.httpsOverHttp({
      proxy: {
        host: 'proxy_ip',
        port: proxyPort,
        rejectUnauthorized: false,
      }
    })
  }
};
ogs(options)
  .then((data) => {
    const { error, result, response } = data;
    console.log('response:', response); // you should see the proxy IP in here
  })


Anyway, your solution fixed the problem. Thanks a lot
