### ISSUE TITLE
how to get the web page icon?

### ISSUE THREAD

**Issue by kaname-png** [jshemas/openGraphScraper#139]
I see that there is no option to get the icon of a web page, the so-called favicon, it is in a <link> element in the header and it can be easily obtained with cheerio.

If there is an option please tell me, if not then it would be great if you added that field since docTitle and docDescription already exist, it would be nice to have docFavicon or docIcon.

**Comment by jshemas** [comment]
Hello. The `favicon` is not part of the [open graph protocol](https://ogp.me/) which is why it's missing. But this is a somewhat simple thing to add. You can now get `favicon` info using `open-graph-scraper@4.11.0`.

**Comment by kaname-png** [comment]
@jshemas nice, thanks!
