### ISSUE TITLE
download limit exceeded, is there a way to not request the html response as well? onlyGetOpenGraphInfo not working

### ISSUE THREAD

**Issue by flatypus** [jshemas/openGraphScraper#150]
I tried scraping reddit.com but found that without setting the downloadLimit to like 10Mb, it won't let me run it, but it seems that the majority of the response is just the html response. Is there a way to only request the results data? I tried {onlyGetOpenGraphInfo:true} in options, but that didn't seem to work.

**Comment by jshemas** [comment]
Hello. I can add a flag for returning the html response.

Note: The `downloadLimit` is option for the main HTTP call made by [GOT](https://github.com/sindresorhus/got) and you will exceed the limit on larger pages. (The idea is to stop users from downloading large files) Adding the flag for html response won't fix this problem.

**Comment by flatypus** [comment]
Ah. I was just trying to get the graph info data for reddit, but i didn't know why it kept exceeding the limit even when I only needed an image and some text.

**Comment by flatypus** [comment]
Oh! I didn't know about the downloadLimit: false setting. Thanks!

**Comment by Murkrage** [comment]
@jshemas `false` isn't an accepted type since it's only allowing `string | undefined`. Is this an error on the types end or is a boolean value just not an actual type we can use?

**Comment by jshemas** [comment]
@Murkrage I've updated the type to allow `false` in `open-graph-scraper@5.0.4`
