### ISSUE TITLE
v5 does not have right types

### ISSUE THREAD

**Issue by iSuslov** [jshemas/openGraphScraper#155]
```
const { result, error } = await ogs({ url: link });
```
In version 5, `result` has type `object`.
`@types/open-graph-scraper` latest version is `4.8.2`

**Comment by jshemas** [comment]
Hello,

I've added the proper types in `open-graph-scraper@5.0.3`.

**Comment by jshemas** [comment]
Closing this for now. Let me know if you have any more issues.
