### ISSUE TITLE
reuslt.twitterImage is improperly typed as string | undefined

### ISSUE THREAD

**Issue by alexng353** [jshemas/openGraphScraper#160]
Typescript claims that it's a string, but it can occasionally be successfully casted to an imageObject type

![image](https://user-images.githubusercontent.com/26424336/216838851-31dc352b-ba70-41b9-a9ad-526bb521ac6a.png)

![image](https://user-images.githubusercontent.com/26424336/216838895-6d089684-039a-4a99-b985-d79b883f3bf8.png)
![image](https://user-images.githubusercontent.com/26424336/216838910-b32b179c-10d3-42b3-b7cf-b87b75193939.png)

**Comment by jshemas** [comment]
Hello. I've added an `twitterImageObject ` type in `open-graph-scraper@5.0.5`.

**Comment by alexng353** [comment]
Thanks m8. There's also a bug that I'm making a new issue on, causing a segmentation fault while using 'jest' and 'supertest' to test an express.js endpoint. I'll link an example repository for recreating it as well. At this point I've dropped back to 4.11.1, since that version does not include the error I mentioned.

**Comment by alexng353** [comment]
#162
