### ISSUE TITLE
 Cannot find module './lib/openGraphScraper' or its corresponding type declarations

### ISSUE THREAD

**Issue by noskovvkirill** [jshemas/openGraphScraper#167]
Hi! For some reason, library fails to run in our repo. This is what I see in my console
```
./node_modules/.pnpm/open-graph-scraper@5.1.0/node_modules/open-graph-scraper/index.ts:3:49
Type error: Cannot find module './lib/openGraphScraper' or its corresponding type declarations.

  1 | /* eslint-disable max-len */
  2 | // eslint-disable-next-line import/no-import-module-exports
> 3 | import setOptionsAndReturnOpenGraphResults from './lib/openGraphScraper';
    |                                                 ^
  4 | 
  5 | /**
  6 |  * `open-graph-scraper` uses [got](https://github.com/sindresorhus/got) for requests and most of
 ELIFECYCLE  Command failed with exit code 1.
```
Any ideas why this might be happening? I suppose it's just a typescript issue because the app is running just fine if I ignore typescript build errors

**Comment by noskovvkirill** [comment]
Solved with changing my import to 
`const ogs = require('open-graph-scraper'); `

**Comment by standup75** [comment]
Thanks, but I think this bug should be solved

**Comment by benoitlahoz** [comment]
Using `vite` as bundler and `import` in Electron, I have this error: 

```
t is not a function
```

Where `t` is obviously the minified version of ogs. 
I also have to use `require`.
