### ISSUE TITLE
Type error in index.ts

### ISSUE THREAD

**Issue by bstyles3** [jshemas/openGraphScraper#172]
When type check runs it throws on `index.ts`:
`This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'`

```
import {
  OpenGraphScraperOptions,
  OgObject,
} from './lib/types';
```

May benefit from being

```
import type {
  OpenGraphScraperOptions,
  OgObject,
} from './lib/types';
```

**Comment by jshemas** [comment]
Hello. This should be fixed in `open-graph-scraper@5.2.1`
