### ISSUE TITLE
Feature request: return html markup

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jshemas/openGraphScraper#19]
It would be very useful to be able to receive full html source of remote site, e.g. as third callback's parameter, like:

```js
ogs(options, function (err, results, source) {
    console.log('source:', source); // This would be full html source of remote site
});
```

**Comment by jshemas** [comment]
This is possible. But if you just want the source of the page, you might be better off scraping it yourself.

**Comment by ktrzeciaknubisa** [comment]
Thanks, but I didn't mean to have "just" the source of a page. Need both OG tags and source :)

**Comment by jshemas** [comment]
Ah. Okay. I'll look into this.

**Comment by jshemas** [comment]
You can now get the source back! Checkout version 2.3.2 of the package.

**Comment by ktrzeciaknubisa** [comment]
Very nice, thank you ! :)
