### ISSUE TITLE
It is better to export SuccessResult and ErrorResult types

### ISSUE THREAD

**Issue by ageofrage** [jshemas/openGraphScraper#196]
I much love this library. But I have small request.

**Is your feature request related to a problem? Please describe.**
I am developing with TS. I want to use `SuccessResult` and `ErrorResult` directly. For example, when Ogs catches an error, I want to typedef the argument to `ErrorResult`.

**Describe the solution you'd like**
Just export `SuccessResult` and `ErrorResult` type.

**Describe alternatives you've considered**
```ts
type OgsResult = ReturnType<typeof ogs> extends Promise<infer T> ? T : never;
```
But this solution cannot extract single SuccessResult or ErrorResult type.

**Additional context**

**Comment by jshemas** [comment]
Good idea. Added in `open-graph-scraper@6.3.0`

**Comment by ageofrage** [comment]
Thanks!☺️
