### ISSUE TITLE
Docker/ docker compose

### ISSUE THREAD

**Issue by mdmm13** [jshemas/openGraphScraper#211]
**Is your feature request related to a problem? Please describe.**
Love the product, but would love to run in docker and access via simple API rather than run locally.

**Describe the solution you'd like**
Dockerfile + docker compose + very simple API

**Describe alternatives you've considered**
LinkPreview, etc.

**Additional context**
Saw it was done in https://github.com/jshemas/openGraphScraper/issues/130, but a reference dockerfile/ docker compose would greatly broaden the appeal.

**Comment by jshemas** [comment]
This could be something fun to make. Would this just be express app with a single route that use `openGraphScraper`?

**Comment by mdmm13** [comment]
Exactly :)
________________________________

**Comment by jshemas** [comment]
Added an example express app. See the docs here -> https://github.com/jshemas/openGraphScraper?tab=readme-ov-file#running-the-example-app
