### ISSUE TITLE
Remove `charset` from result JSON

### ISSUE THREAD

**Issue by cm-dyoshikawa** [jshemas/openGraphScraper#212]
**Is your feature request related to a problem? Please describe.**

https://github.com/jshemas/openGraphScraper/pull/206
The change has resulted in the openGraphScraper working very well within our product.

As a result, I believe that the charset in the result JSON is now unnecessary.

**Describe the solution you'd like**
I would like to make a change to remove the charset from the result. If the maintainer agrees, I will undertake the work.

**Describe alternatives you've considered**
Maintain the current behavior without any changes.

**Additional context**

**Comment by jshemas** [comment]
Hello. Someone might want that info and it doesn't hurt to keep it in.

**Comment by cm-dyoshikawa** [comment]
@jshemas If you say so, then I understand. Thank you.
