### ISSUE TITLE
Follow manifest for favicon

### ISSUE THREAD

**Issue by psugihara** [jshemas/openGraphScraper#221]
**Is your feature request related to a problem? Please describe.**
I'm scraping favicons for company websites. This works pretty well with openGraphScraper but I found an edge case that is not handled.

Here's the example site where the favicon is not found but my browser finds it from [the manifest](https://shop.mercaso.com/site.webmanifest):
https://shop.mercaso.com

**Describe the solution you'd like**
Get favicon from web manifest if it can't be found otherwise.

**Describe alternatives you've considered**
I could use `parse-favicon`, but I like the OG image fallbacks this package provides.

**Additional context**

<img width="632" alt="Screenshot 2024-06-02 at 3 26 43 PM" src="https://github.com/jshemas/openGraphScraper/assets/282016/76446fb1-415b-499b-ba4d-3ae61a28efa2">

**Comment by jshemas** [comment]
Hello.  `open-graph-scraper@6.5.2` should fix this use case. Let me know if I need to add anymore fall backs.

**Comment by jshemas** [comment]
Closing this for now, let me know if you have any more issues.

**Comment by psugihara** [comment]
cool. appreciate the quick fix!
