### ISSUE TITLE
Please provide ESM export

### ISSUE THREAD

**Issue by michalkvasnicak** [jshemas/openGraphScraper#223]
It is hard to use this package when producing ESM native modules for nodejs 18+. 

When you configure a project to use `moduleResolution: 'NodeNext'` and `module: 'NodeNext'`, you will get `TS2349` error saying that the `open-graph-scraper` has no call signatures. That is the result of improper typings produced that are pretending to be ESM compatible but in reality they aren't and they would break the runtime.

**Comment by jshemas** [comment]
Unable to reproduce the issue. Please follow the `Bug report` template next time and give a full working example of your issue.
