### ISSUE TITLE
Not retrieving focus product images with amazon links

### ISSUE THREAD

**Issue by ngocnguyenminh-amela** [jshemas/openGraphScraper#225]
**Describe the bug**
After using ogs({url}) with the url being the amazon link. I received an image link that has nothing to do with the product link
Here is Amazon link: 
https://www.amazon.com/VILOCY-Sneakers-Oxfords-Business-Lightweight/dp/B0B3TCWS1J
![image](https://github.com/jshemas/openGraphScraper/assets/152826862/6d38849d-998b-4b8d-9fad-182c95b612f0)

And here is my response: 
![image](https://github.com/jshemas/openGraphScraper/assets/152826862/04c5c3af-2a41-4bbd-aa54-cc2f50a53c53)

How can I get the return link to the photo of this product?

 - OS: All
 - Node Version: 20.3.1
 - openGraphScraper Version:6.5.2

**Comment by jshemas** [comment]
Hello. Looks like amazon is blocking your requests and giving you a captcha page. There isn't anything OGS can do about that, but you can try setting your `User Agent` and using a proxy. See https://github.com/jshemas/openGraphScraper?tab=readme-ov-file#user-agent-example for more info.

Side note: `www.amazon.com` doesn't have any open graph tags, so even if you were able to make a request it would look something like this:

```
result: {
  ogTitle: "Amazon.com | VILOCY Men's Mesh Dress Sneakers Oxfords Business Casual Walking Shoes Tennis Comfortable | Fashion Sneakers",
  ogImage: [
    {
      url: 'https://m.media-amazon.com/images/G/01/gno/sprites/nav-sprite-global-1x-reorg-privacy._CB587940754_.png',
      type: 'png'
    },
    {
      url: 'https://m.media-amazon.com/images/G/01/nav2/images/gui/amazon-fashion-store-new._CB485923950_.png',
      type: 'png'
    },
    {
      url: 'https://m.media-amazon.com/images/G/01/AMAZON_FASHION/2021/PRIME_WARDROBE/REBRAND/en_US/TBYB_Right_Nav._CB639761007_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/41bjw4UkWnL._AC_US40_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/31yCBzCkr8L._AC_US40_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/41KHDoRbE2L._AC_US40_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/41k3xXfpXDL._AC_US40_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/31F93qtWU8L._AC_US40_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/31mmCiolGNL._AC_US40_.jpg',
      type: 'jpg'
    },
    {
      url: 'https://m.media-amazon.com/images/I/81nA6iXMRJL.SS40_PKmb-play-button-overlay-thumb_.jpg',
      type: 'jpg'
    }
  ],
  ogLocale: 'en-us',
  ogUrl: 'https://www.amazon.com/VILOCY-Sneakers-Oxfords-Business-Casual/dp/B0B3T9Q4VY',
  charset: 'utf-8',
  requestUrl: 'https://www.amazon.com/VILOCY-Sneakers-Oxfords-Business-Lightweight/dp/B0B3TCWS1J',
  success: true
}
```

**Comment by ngocnguyenminh-amela** [comment]
Thanks for the help. I also realized that in the amazon link there is no "og" tag. I think I will take a default image to show. I fixed the problem of showing captcha text when using user-agent as you instructed. Thank you!
