### ISSUE TITLE
Webpack error after upgrading to 6.6.0

### ISSUE THREAD

**Issue by yhuang1211** [jshemas/openGraphScraper#227]
After upgrading to 6.6.0
Nextjs does not build and throw the following error

Step #0: Module not found: Default condition should be last one
Step #0: 
Step #0: https://nextjs.org/docs/messages/module-not-found
Step #0: 
Step #0: 
Step #0: > Build failed because of webpack errors

 - OS: Mac/Linux
 - Node Version: 20
 - openGraphScraper Version: 6.6.0

**Comment by jshemas** [comment]
This should be fixed in `open-graph-scraper@6.6.1`
