### ISSUE TITLE
Feature request: parse from string rather than url

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [jshemas/openGraphScraper#23]
The module fails for the following link:

> http://www.nytimes.com/2016/09/01/arts/design/gallery-hopes-to-sell-kanye-wests-famous-sculpture-for-4-million.html?_r=0

This is because it does multiple redirects:

> curl -v -L http://nytimes.com/2016/09/01/arts/design/gallery-hopes-to-sell-kanye-wests-famous-sculpture-for-4-million.html?_r=0
> ...
> Connection #7 to host myaccount.nytimes.com left intact

So I can use curl for getting the html contents myself, but I would like to use the scraper to parse from string.

**Comment by jshemas** [comment]
Hello! This is a neat idea! I'll look into it!

**Comment by jshemas** [comment]
Adding a test for this in https://github.com/jshemas/openGraphScraper/pull/48

**Comment by jshemas** [comment]
available in `3.0.0`

**Comment by ejb** [comment]
Hi, I can't see this feature documented anywhere, and I can't see it in the source code either. Am I missing something?

**Comment by jshemas** [comment]
Hello, when I address this issue I fix the problem with the scraper not following redirects... But it looks like there was more to it. 

Thanks for making the PR!

**Comment by jshemas** [comment]
PR had been merged. Changes can be found in `open-graph-scraper@3.1.0`
