### ISSUE TITLE
Typescript Export Assignment

### ISSUE THREAD

**Issue by Sydney-o9** [jshemas/openGraphScraper#237]
**Describe the bug**
There is a regression in `^6.6` for Tyepscript users.

![image](https://github.com/user-attachments/assets/f7fac176-9d80-4f40-af01-62c48b15e53a)

We had to downgrade to `^6.5` to transpile properly
![image](https://github.com/user-attachments/assets/e1f580b8-1934-4c42-9fae-d62d5543ec0b)

**To Reproduce**

Use `^6.6` and build `$ tsc`

**Expected behavior**
It should compile

**Actual behavior**
It doesn't compile with error:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/3568ddb6-8ee0-4e93-86c8-364dfd9199c8">

> The issue arises because the code is trying to mix export default with export =, which is not allowed in TypeScript. In a module, you cannot use both export default and export = together.

 - OS: `MacOS`
 - Node Version: `v18.20.1`
 - openGraphScraper Version: `^6.6` and `^6.7`

**Comment by jshemas** [comment]
That was added fix ESM imports for `module/moduleResolution = NodeNext` projects. I'm not sure if there is a better way to fix that problem.

**Comment by jshemas** [comment]
Hello. This should be fixed in `open-graph-scraper@6.7.1`

**Comment by nekochan0122** [comment]
> Hello. This should be fixed in `open-graph-scraper@6.7.1`

Hello, the types `SuccessResult` and `ErrorResult` are not exported in `6.7.1`

![image](https://github.com/user-attachments/assets/6face4a7-b414-4d6f-aaad-a429832e25b5)

**Comment by jshemas** [comment]
@nekochan0122 These types were moved into the `types` file. So you can do something like `import type { SuccessResult, ErrorResult } from 'open-graph-scraper/types/lib/types';`

**Comment by nekochan0122** [comment]
@jshemas Thx for the reply, but I still got the errors.

![image](https://github.com/user-attachments/assets/94e06dee-ef64-408e-8add-baffa09ddf43)

**Comment by jshemas** [comment]
`import type { SuccessResult, ErrorResult } from 'open-graph-scraper/types/lib/types';` should now work in `open-graph-scraper@6.7.2`

![image](https://github.com/user-attachments/assets/f99f9127-3e90-4397-bcaf-ffcc46340e59)

**Comment by nekochan0122** [comment]
Will be more nice if the import path can be shorter :
`import type { SuccessResult, ErrorResult } from 'open-graph-scraper/types`

or :
`import type { SuccessResult, ErrorResult } from 'open-graph-scraper`

https://github.com/jshemas/openGraphScraper/blob/0d01a6bed4a5d810906c5a722fdd554d62715fb2/package.json#L14

**Comment by jshemas** [comment]
@nekochan0122 Good idea. Changes are live in `open-graph-scraper@6.8.0`. Open a new issue if you have any more problems.
