### ISSUE TITLE
Opengraph image shows a pdf icon in this case

### ISSUE THREAD

**Issue by SimonSiefke** [jshemas/openGraphScraper#238]
**Describe the bug**
The open-graph-scraper falls back to returning the first image in the page as the opengraph image. Sometimes this could be undesirable as the first image in the page could be a random icon like a pdf icon.

**To Reproduce**
1. Use opengraph scraper to request data for https://lernplattform.involas.com/course/view.php?id=13&section=1
2. Notice that as ogImage a image of a pdf is returned

**Expected behavior**
When no ogImage is available, no image is returned.

**Actual behavior**
When no ogImage is available, the first image in the page is returned. Sometimes this could be misleading, as the first image could just be a random icon like a pdf icon. 

**Screenshots**
![ogs-data](https://github.com/user-attachments/assets/196dd655-bc3d-47af-bc55-6d51a2d69207)

**Additional context**

open-graph-scraper provides an option `onlyGetOpenGraphInfo: true` that where it will not fallback to the first image it finds in the html. It does indeed solve the image problem, but returns much less data for title and description. 

Perhaps it might be a good idea to add an option like `onlyGetOpenGraphInfo: "image"`, so that lots of data is returned for title and description and still the image would always be accurate (e.g. not a random icon sometimes like a pdf icon)

**Additional Information**

On https://www.opengraph.xyz, no ogImage is displayed for https://lernplattform.involas.com/course/view.php?id=13&section=1. 

![og-image-90](https://github.com/user-attachments/assets/94c76007-3e13-40cf-bb53-e3803f88aa71)

 - OS: Linux
 - Node Version:22

 - openGraphScraper Version: 6.7.0

**Comment by jshemas** [comment]
Hello. If a page doesn't have a real `ogImage`, this package will just grab the first 10 images it finds. There is no way of knowing which image is the most meaningful. 

Doing something like `onlyGetOpenGraphInfo: "image"` seems like neat idea. I might do that in the future.

**Comment by jshemas** [comment]
changes are live in `open-graph-scraper@6.8.0`
