### ISSUE TITLE
Issue /w Youtube Requests in Production

### ISSUE THREAD

**Issue by shihfu** [jshemas/openGraphScraper#242]
## Describe the bug
As stated in the title, I am having issues /w getting Youtube details in production. This was working previously when running from both localhost or production. I'm not sure what has changed.

This behaviour is strictly just for Youtube links. I am getting consistent responses with other links in both localhost and production.

## Expected behavior
Youtube response details from localhost and production should be the same.

## Actual behavior
This is the response I am getting back when running on http://localhost:3010/
```
{
  result: {
    success: true,
    ogSiteName: 'YouTube',
    ogUrl: 'https://www.youtube.com/watch?v=dT1iV8uN1nk',
    ogTitle: 'Behavior Expert: How to Trick a Liar Into Accidentally Telling The Truth',
    ogDescription: "If you like this episode, you'll love this episode about AI with Google's DeepMind co-founder: https://youtu.be/Wn244ffkc8ITopics:0:00 - Intro0:41 - Body lan...",
    alIosAppStoreId: '544007664',
    alIosAppName: 'YouTube',
    alIosUrl: 'vnd.youtube://www.youtube.com/watch?v=dT1iV8uN1nk&feature=applinks',
    alAndroidUrl: 'vnd.youtube://www.youtube.com/watch?v=dT1iV8uN1nk&feature=applinks',
    alWebUrl: 'http://www.youtube.com/watch?v=dT1iV8uN1nk&feature=applinks',
    ogType: 'video.other',
    ogVideoSecureURL: 'https://www.youtube.com/embed/dT1iV8uN1nk',
    alAndroidAppName: 'YouTube',
    alAndroidPackage: 'com.google.android.youtube',
    ogVideoTag: 'nsa',
    fbAppId: '87741124305',
    twitterCard: 'player',
    twitterSite: '@youtube',
    twitterUrl: 'https://www.youtube.com/watch?v=dT1iV8uN1nk',
    twitterTitle: 'Behavior Expert: How to Trick a Liar Into Accidentally Telling The Truth',
    twitterDescription: "If you like this episode, you'll love this episode about AI with Google's DeepMind co-founder: https://youtu.be/Wn244ffkc8ITopics:0:00 - Intro0:41 - Body lan...",
    twitterAppNameiPhone: 'YouTube',
    twitterAppIdiPhone: '544007664',
    twitterAppNameiPad: 'YouTube',
    twitterAppIdiPad: '544007664',
    twitterAppUrliPhone: 'vnd.youtube://www.youtube.com/watch?v=dT1iV8uN1nk&feature=applinks',
    twitterAppUrliPad: 'vnd.youtube://www.youtube.com/watch?v=dT1iV8uN1nk&feature=applinks',
    twitterAppNameGooglePlay: 'YouTube',
    twitterAppIdGooglePlay: 'com.google.android.youtube',
    twitterAppUrlGooglePlay: 'https://www.youtube.com/watch?v=dT1iV8uN1nk',
    ogImage: [ [Object] ],
    ogVideo: [ [Object] ],
    twitterImage: [ [Object] ],
    twitterPlayer: [ [Object] ],
    ogLocale: 'en',
    ogDate: '2024-08-07T09:00:40-07:00',
    favicon: 'https://www.youtube.com/s/desktop/d44eab58/img/favicon.ico',
    charset: 'UTF-8',
    jsonLD: [ [Object] ],
    requestUrl: 'https://www.youtube.com/watch?v=dT1iV8uN1nk'
  }
}
```

And this is the response I am getting back in production.

```
{
  result: {
    success: true,
    ogTitle: ' - YouTube',
    ogDescription: 'Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.',
    ogLocale: 'en',
    ogUrl: 'undefined',
    favicon: 'https://www.youtube.com/s/desktop/d44eab58/img/favicon.ico',
    charset: 'UTF-8',
    requestUrl: 'https://www.youtube.com/watch?v=dT1iV8uN1nk'
  }
}
```

**Comment by reeshabhranjan** [comment]
Facing this issue as well in production.

**Comment by jshemas** [comment]
Youtube is probably blocking the request. See [user-agent-example](https://github.com/jshemas/openGraphScraper?tab=readme-ov-file#user-agent-example) section on ways around this.

**Comment by murtuzaalisurti** [comment]
experienced this today, wasted 3 hours until I found this

**Comment by reeshabhranjan** [comment]
A custom user-agent is not working for me. @murtuzaalisurti which user-agent did you end up using?

**Comment by murtuzaalisurti** [comment]
@reeshabhranjan I didn't try it yet, because I am planning to use the official youtube API to fetch the metadata. https://developers.google.com/youtube/v3/docs/videos

**Comment by murtuzaalisurti** [comment]
@reeshabhranjan tried, didn't work for me, seems the the official API or a third party service/proxy is the way to go.

**Comment by reeshabhranjan** [comment]
@murtuzaalisurti Yeah, seems like the AWS servers are blacklisted by the service this library uses.

**Comment by reeshabhranjan** [comment]
@jshemas technically this issue is not solved with the solution you posted.

**Comment by murtuzaalisurti** [comment]
@reeshabhranjan @jshemas  ended up using the official google API to fetch the metadata. However it does not give you everything related to opengraph.

```js
import { google } from "googleapis";

const yt_metadata = await google.youtube("v3").videos.list({
    key: import.meta.env.GOOGLE_API_KEY,
    id: [<video_id>],
    part: ["snippet"],
});
```

**Comment by shihfu** [comment]
> @reeshabhranjan @jshemas ended up using the official google API to fetch the metadata. However it does not give you everything related to opengraph.
> 
> ```js
> import { google } from "googleapis";
> 
> const yt_metadata = await google.youtube("v3").videos.list({
>     key: import.meta.env.GOOGLE_API_KEY,
>     id: [<video_id>],
>     part: ["snippet"],
> });
> ```

Can you share the output of this query? And what OG data is missing?

**Comment by murtuzaalisurti** [comment]
@shihfu sure, you can find it here https://developers.google.com/youtube/v3/docs/videos#resource-representation

**Comment by shihfu** [comment]
Seems like there's been some kind of crackdown @ Youtube recently. `youtube-transcript` package is also no longer working and as of today, Firecrawl no longer supports Youtube due to privacy restrictions.

Youtube API sounds like the reasonable path to go down, but I was a little hesitant due to scaling concerns and complexity. So I did some digging and found that they provide an oEmbed endpoint.

You just have to structure your request like the following:
```
https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=dQw4w9WgXcQ&format=json
```

I don't have much experience with oEmbed though. Does anyone know if there are drawbacks to this method?

**Comment by bramses** [comment]
Running into same issue, same thing is happening to Reddit URLs (kinda)

```js
(base) bram@brams-macbook the-things-i-do-for-titles % curl -X POST https://.../get-title \
     -H "Content-Type: application/json" \
     -d '{"url": "https://www.reddit.com/r/applehelp/s/CRbMf6lYih"}'
{"result":"Reddit"}%                                                                                                                                
(base) bram@brams-macbook the-things-i-do-for-titles % curl -X POST http://localhost:3001/get-title \
     -H "Content-Type: application/json" \
     -d '{"url": "https://www.reddit.com/r/applehelp/s/CRbMf6lYih"}'
{"result":"Reddit - Dive into anything"}% 
```
