### ISSUE TITLE
wait/sleep/delay for og to be populated on the webpage?

### ISSUE THREAD

**Issue by yuis-ice** [jshemas/openGraphScraper#251]
An example page that delays the open graph data to be shown up: [https://jp.mercari.com/item/m99319551688](https://jp.mercari.com/item/m99319551688)

In the above example, landing to the page, wait for 3 seconds or so, now you can get the OG (and title, meta description etc too)

I think such sites often uses client-side JS heavy stacks that takes some time. E.g. React, Vue etc. 

So is such option already implemented on the library, or possible to implement?

**Comment by jshemas** [comment]
Hello. This isn't possible without significant effort. `openGraphScraper` uses Node's Fetch API(undici) to make http requests. To render client-side JS heavy sites you would need something like [puppeteer](https://pptr.dev/). You could have `puppeteer` render the page and then feed the HTML into `openGraphScraper`.
