### ISSUE TITLE
Undici requirement breaks browsers and Edge runtimes

### ISSUE THREAD

**Issue by dom96** [jshemas/openGraphScraper#252]
The Undici requirement is present even when passing the HTML directly to `ogs` and means that this library cannot be used in non-Node runtimes.

Switching to using the `fetch` API would solve that and make this library usable in browsers and Edge runtimes.

**Comment by jshemas** [comment]
Hello, please check out `open-graph-scraper-lite` if you can't use the `fetch` API.
