### ISSUE TITLE
Issue with handling encoding

### ISSUE THREAD

**Issue by justmobilize** [jshemas/openGraphScraper#29]
Currently for your recent adds to handle encoding, you are checking that `options.encoding === null` to see if you should try to detect the charset, but this by default is `undefined` so doesn't run. This should eighter have a default set, or be `if (options.encoding === null || options.encoding === undefined)`

**Comment by jshemas** [comment]
I looked into this a bit. It looks like setting `encoding` to true or utf-8 will break other things. I'm not really sure if this is a issue or not.

**Comment by justmobilize** [comment]
I'm currently setting `encoding` to null so it auto detects. I didn't look at other options since I want it to auto detect. What does it break? I'm happy to help and possibly send in a PR

**Comment by jshemas** [comment]
Okay, I updating the package to default `encoding` to `null`. Changes are in `2.4.1`

**Comment by patrikhermansson** [comment]
Hi,
Not 100% this is the same issue but related to encoding. I get 'Error: Encoding not recognized: 'ansi_x3' (searched as: 'ansix3') ' now and then, looks like an issue with iconv. Throws an error which is a bit unfortunate. ansi_x3 is an alias for utf-8. Possible to handle this in open-graph-scraper, or at least not throw?

**Comment by jshemas** [comment]
@patrikhermansson please make a new issue and add an example URL that will cause this issue.
