### ISSUE TITLE
Error param in callback is not an error object

### ISSUE THREAD

**Issue by tmaslen** [jshemas/openGraphScraper#3]
Hello,

Really liking openGraphScraper and finding it useful in my project, thanks for making it.

When I get the occasional error from a graph request, an error object is passed but its not a standard JavaScript error.  In the documentation it shows dealing with an error like this...

```
console.log("err:",err);
```

But this will output as `err: err` when there is an error.

Is there any chance you could throw a more meaningful error message or give a clearer indication of what is happening when the requested webpage has a problem?

Thanks again for making openGraphScraper,
/t

**Comment by YoannB** [comment]
Hi,

I read code of openGraphScraper and found this : 

```
callback('err',{ success: false, err: 'Invalid URL' })
```

So if you have `err`, you can have more info in the second parameter `results`, like in example :

```
ogs(options, function(err, results) {
    console.log("err:",err);
    console.log("results:",results);
    console.log("message error:",results.err);
});
```
++

**Comment by jshemas** [comment]
YoannB is right, you have to look in the 'results' object to see the real error.
