### ISSUE TITLE
Feature request: return content type for non-html requests

### ISSUE THREAD

**Issue by thg1101** [jshemas/openGraphScraper#36]
Since the request has already been made, it would help to return the content type encountered when scraping resources that aren't HTML (such as images, media, etc).
This could be made as an extra parameter in the results object, so as to not break existing deployments.

**Comment by jshemas** [comment]
Hello,

If you are using the latest version of the package(`2.5.0`) you can look the third param which is the response  object of the call. `response.headers['content-type']` will contain what you are looking for.

**Comment by thg1101** [comment]
Perfect. Upgraded and modified my service, works like a charm. Thank you!
