### ISSUE TITLE
Not installing with node 7

### ISSUE THREAD

**Issue by saggiyogesh** [jshemas/openGraphScraper#37]
Since in package.json, `engines` are configured for node 6.x, yarn is not allowing to install it. 
Please fix this.

**Comment by jshemas** [comment]
I'm only supporting LTS at this time. (`6.10.1` at this time.)

https://nodejs.org/en/

**Comment by jshemas** [comment]
This PR might solve your problem. https://github.com/jshemas/openGraphScraper/pull/39
