### ISSUE TITLE
Return original request error

### ISSUE THREAD

**Issue by moehlone** [jshemas/openGraphScraper#38]
Hi,

it would be very useful if any errors of the internal request could be passed back in the callback.

Example:

The internal request has the following error:
```javascript
{ Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
```

The error passed in the callback:
```
true
```

Troubleshooting is not possible in this way, without adding logs to the module :-(

**Comment by jshemas** [comment]
Hello!

Can you give me the URL that is causing this issue?

Also I have adding `errorDetails` in the return object in `open-graph-scraper@2.5.3`

example:
```
result: { err: 'Page Not Found',
  success: false,
  errorDetails: 
   { Error: getaddrinfo ENOTFOUND mytesturl.com mytesturl.com:80
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'mytesturl.com',
     host: 'mytesturl.com',
     port: 80 } }
```

**Comment by moehlone** [comment]
Hi,

sorry - I was on vacation for the last weeks.

I expected those details in the first error callback parameter and did not noticed
the errorDetails within the result object.

Thank you!
