### ISSUE TITLE
cors!!!

### ISSUE THREAD

**Issue by leeeejuy** [jshemas/openGraphScraper#42]
error:XMLHttpRequest cannot load https://www.naver.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'localhost:8000' is therefore not allowed access. The response had HTTP status code 404.

how should i do?

**Comment by leeeejuy** [comment]
Must scrape an HTML page error...

**Comment by jshemas** [comment]
Not really sure what you are asking. I'm able to scrape `https://www.naver.com/`

Can you give me a code example?

**Comment by cfinckler** [comment]
Are you trying to use this scraping library within the browser? That ist not possible. Inside the browser you cannot access other hosts.If you need the result in the browser you must implement a backend interface which uses this library.

**Comment by jamigibbs** [comment]
@leeeejuy This might help clear things up for you: https://stackoverflow.com/questions/45569805/fetching-open-graph-metadata-with-create-react-app

**Comment by jshemas** [comment]
going to close this as a non-issue. let me know if you have any other problems.
