### ISSUE TITLE
content-type text/html misread

### ISSUE THREAD

**Issue by feedyourmind** [jshemas/openGraphScraper#45]
Sometimes it thinks a response is not text/html, even though it is. 
For example, with https://www.namecheap.com/ , a very popular dns provider
It should be able to give the ogs info, but it fails with error. 
There is a check in the code: 
else if (!(response && response.headers && response.headers['content-type'] && response.headers['content-type'].indexOf('text/html') !== -1)) {
        callback('Must scrape an HTML page', null, response);

That should be relaxed somehow, or cater for scenarios like the example above

**Comment by jshemas** [comment]
Very interesting! I'll have to think about this for a bit.

**Comment by jshemas** [comment]
In https://github.com/jshemas/openGraphScraper/pull/48 i've update the way it checks for HTML pages and added a test for namecheap.com

**Comment by jshemas** [comment]
available in `3.0.0`
