### ISSUE TITLE
forbes.com articles are allways showing home page OG data

### ISSUE THREAD

**Issue by cccaballero** [jshemas/openGraphScraper#46]
Forbes shows first the home page, and after a few seconds it redirects to the article page, so openGraphScraper is loading the home page OG tags, but facebook (by example) show the proper OG tags if I use the article link

**Comment by jshemas** [comment]
Hello!

Thanks for opening a issue. Can you give me a example URL to test?

In https://github.com/jshemas/openGraphScraper/pull/48 I added a test for `https://www.forbes.com/sites/kenkam/2017/09/28/3-stocks-like-apple-was-10-years-ago-tesla-nvidia-and-alibaba/#2636f6c2f0fa` and that seems to work.

**Comment by jshemas** [comment]
available in `3.0.0`
