### ISSUE TITLE
Consider starting a changelog or using tags/releases

### ISSUE THREAD

**Issue by suprMax** [jshemas/openGraphScraper#50]
Hi! Thanks for the scraper, gets the job done so far! I've been using it for about a year now and after you released your last version I tried looking for a changelog and didn't see any. Because of this the change from `err` to `error` in the error response was unexpected for me and lead to some crashes. I still have no idea if anything else changed.

Could you please provide a summary of changes between previous and current version, and perhaps start a "CHANGELOG.md" file?

**Comment by jshemas** [comment]
Thank you for using my module! I'm sorry my latest updates caused issues for you. 

Adding a `CHANGELOG.md` is a great idea! You can see it here: https://github.com/jshemas/openGraphScraper/blob/master/CHANGELOG.md
