### ISSUE TITLE
open-graph-scraper@3.1.0 is not published

### ISSUE THREAD

**Issue by mrose17** [jshemas/openGraphScraper#52]
the most recent version is `open-graph-scraper@3.0.2` which lacks the useful `html` option. help!

**Comment by jshemas** [comment]
`3.1.0` is now on NPM. Thanks for making this issue!

**Comment by mrose17** [comment]
thank you fo the wonderful package!

**Comment by jshemas** [comment]
Welcome! Let me know if you need anything else!
