### ISSUE TITLE
Add properties

### ISSUE THREAD

**Issue by yakimko** [jshemas/openGraphScraper#53]
I found the following meta tags. Could you please add them?

```
<meta property="og:price:amount" content="64.00"/>
<meta property="og:price:currency" content="USD"/>
<meta property="og:availability" content="InStock"/>
```

**Comment by jshemas** [comment]
Hello!

Making that change should be very easy. Do you have a example website that has those meta tags?

**Comment by yakimko** [comment]
Hi! 
Here you go https://www.michaelkors.com/mirabel-suede-sandal/_/R-US_40T6MBMS1S?color=1587. 
I think they can have the same output properties as for og:product:*

**Comment by jshemas** [comment]
Thanks for the link. Updating code to check for those meta tags.

Changes can be found in `open-graph-scraper@3.1.2`
