### ISSUE TITLE
Suggestion: add retry functionality

### ISSUE THREAD

**Issue by ljtijhuis** [jshemas/openGraphScraper#55]
Let me start of with: great package! A happy user here :)

Then my problem: we are doing multiple requests at the same time and running in some `ESOCKETTIMEDOUT` errors. I did some tricks to improve this (for example improving the `UV_THREADPOOL_SIZE`), but cannot completely get rid of them. I am now building functionality to do a retry after some seconds, with a max retry setting. Would be awesome if there was a property in this package we could set to do the same.

Good idea? I have seen some `request` packages that add this functionality for recoverable errors to `request` as well.

**Comment by jshemas** [comment]
I think this is great idea! Do you have any examples for this? You are welcome to open a PR if you want.

**Comment by ljtijhuis** [comment]
Will have a look 👍

**Comment by jshemas** [comment]
In version `4.0.0` of ogs, I have updated the module to use `got.js` and that retry functionality build in.

More info: https://www.npmjs.com/package/got#retry
