### ISSUE TITLE
Didn't get tags correctly

### ISSUE THREAD

**Issue by akirasakata** [jshemas/openGraphScraper#63]
Didn't get information correctly from "http://www.uniqlo.com/jp/store/goods/182567-08".
It is sample.

Below is test result 
{ ogTitle: '{{meta.title}}',
     ogType: 'website',
     ogUrl: '{{meta.absUrl}}',
     ogSiteName: 'ユニクロ(UNIQLO)オンラインストア',
     ogDescription: '{{meta.description}}',
     ogImage: { url: '{{meta.ogImage}}', width: null, height: null, type: null } },
  success: true,
  requestUrl: 'http://www.uniqlo.com/jp/store/feature_mb/uq/fe_list/ut/build/kids?quickviewproduct=405988001' }

**Comment by jshemas** [comment]
That looks like some kind of templating (like handlebars.js) that relays on JavaScript to run. `openGraphScraper` does not currently support those kinds of pages.

Using something like `puppeteer` might fix this issue.

https://github.com/GoogleChrome/puppeteer

**Comment by akirasakata** [comment]
Thanks a lot. I understood what it mean.
