### ISSUE TITLE
Can this be used on client side?

### ISSUE THREAD

**Issue by santo-cold** [jshemas/openGraphScraper#65]

**Comment by jshemas** [comment]
I haven't tried this, but I believe it will work. Let me know if you have any issues.

**Comment by CinKon** [comment]
I tried, but get the following errors:

![bildschirmfoto 2018-09-06 um 13 02 53](https://user-images.githubusercontent.com/3854991/45153700-3a5b1c00-b1d5-11e8-90e0-e6df25ca95fc.jpg)

**Comment by jshemas** [comment]
@CinKon can you make a new issue and add steps to reproduce?

**Comment by olivierlourme** [comment]
@santo-cold I made this module work in an Angular client app. I use https://cors.io/?url_to_reach to get around cors policy. Everything is fine except that my vendor.bundle.js went from 1.2 MB to 3.1 MB !!! @jshemas It's too big for a client.

**Comment by jshemas** [comment]
@olivierlourme I'm guessing that is coming from `cheerio` or `request`. Nothing I can really do about that.
