### ISSUE TITLE
How to scrap author, publisher meta info

### ISSUE THREAD

**Issue by ChengYuHin99** [jshemas/openGraphScraper#68]
Hi
How to scrap author, publisher meta info etc?
It will be better to set custom meta key for scrapping.
Is there any option for  this?
If so, please let me know.

Thanks.

**Comment by jshemas** [comment]
Right now there isn't any way of setting custom meta key. Feel free to open a pull request for that feature!

**Comment by jshemas** [comment]
You can now grab custom meta tags in `open-graph-scraper@4.5.0`
