### ISSUE TITLE
Return response in promise

### ISSUE THREAD

**Issue by mbodge** [jshemas/openGraphScraper#72]
Is it possible to return the full response when you're using the library with promises? It seems like that doesn't get returned.

```
ogs(options)
  .then((results, response) => {
    console.log('results:', results);
    //console.log('response', response);
  })
```

**Comment by steve1000** [comment]
You can use node's [promisify](https://nodejs.org/api/util.html#util_util_promisify_original) utility (Node 8.0+).

Something like this worked for me:

```javascript
const { promisify } = require('util');
let ogs = require('open-graph-scraper');

ogs = promisify(ogs).bind(ogs);
const options = { 'url': 'https://website.com' };

ogs(options).then(result => console.log('result', result));
```

`async/await` should work too.

**Comment by jshemas** [comment]
In version `4.0.0` of ogs, it will now send back the `response` using promises.
