### ISSUE TITLE
How to avoid mixed content when pulling og-image

### ISSUE THREAD

**Issue by maki3000** [jshemas/openGraphScraper#76]
When an OG-image is served over HTTP instead of HTTPS the browser complains about mixed content. Is there a way to avoid that?

**Comment by jshemas** [comment]
Do you have an example of this?

**Comment by maki3000** [comment]
For example CSS-Tricks https://css-tricks.com has:
`<meta property="og:image" content="https://css-tricks.com/wp-content/uploads/2014/03/css-tricks-star.png" />`
and
`<meta property="og:image:secure_url" content="https://css-tricks.com/wp-content/uploads/2014/03/css-tricks-star.png" />`.
The openGraphScraper doesn't take the secure_url. It's hard to give you a working example, as our platform, where we use the openGraphScraper, isn't public yet.

I mean, we could always check for https in the provided image URL and then don't show the image, but if there is a secure_url, the script should go for that.

**Comment by maki3000** [comment]
We now don't show images which are served over HTTP. But we check if a HTTPS resource is available like this:
```
// check if HTTPS version of image exists
    if (!metadata.ogImage.url.startsWith('https') && metadata.ogImage.url.includes('http')) {
        let testImage = new Image();
        testImage.src = metadata.ogImage.url.replace('http', 'https');
        if (testImage.width !== 0) {
            metadata.ogImage.url = metadata.ogImage.url.replace('http', 'https');
        }
    }
```
I really don't know if that is a good solution, but it works...

**Comment by justinharkey** [comment]
@maki3000 I know this is very old but you could always serve the image without a protocol. 

`testImage.src = metadata.ogImage.url.replace(/https?:/g, '');`

This would result in `//example.com/image.jpg`, No more mixed content warnings.

**Comment by jshemas** [comment]
Hello, I don't really want change any of the page data in ogs. But I think the above answer will solve your problem.
