### ISSUE TITLE
Medium short links are not supported

### ISSUE THREAD

**Issue by d-ivashchuk** [jshemas/openGraphScraper#77]
Hey! Thanks a lot for your library, I am totally enjoying it and using in my telegram bot application. Stumbled on an issue and wanted to get your opinion:

https://link.medium.com/O8Wg18lGwW

The above link appears to have no data on promise resolve but success is still true. It redirects to completely different page and some openGraph checkers yield no results on it, although some return all the correct data. Is it an known issue, or I am just doing smth wrong?

Thanks a lot for your help and time. Cheers!

**Comment by d-ivashchuk** [comment]
To anyone landing on this issue keep in mind that medium links from the app redirect on the client which make it hard to get open graph tags. You need to download the html for that page and grab a final link from there!

**Comment by jshemas** [comment]
Hello,

This is the same issue as https://github.com/jshemas/openGraphScraper/issues/75 so i'm going to close this issue.
