### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by tsmith123** [jshemas/openGraphScraper#8]
Using the following URL I'm getting a page not found error but when I navigate to the URL in my browser there is no issue. Is there a reason for this? I've had it working with other URLs.

URL: http://www.wemeanbusinesslondon.com/blog/2016/5/10/the-entrepreneur-spiration-series-going-nuts-for-pip-nut

**Comment by jshemas** [comment]
Hello,

Just put in a fix! Please update to version `2.0.6` 

Let me know if that works for you now.

**Comment by tsmith123** [comment]
Yeah this appears to be sorted now - thanks
