### ISSUE TITLE
stuck nodejs when non html pages specified

### ISSUE THREAD

**Issue by r-mizuno** [jshemas/openGraphScraper#81]
If page other than html is specified and the url does not end with an extension, nodejs may get stuck.

For example, the following url:
http://rcc.jp/event/daiku/images/flier.pdf?191101

**Comment by brum1975** [comment]
I have similar issue for the following podcast/mp3 url
https://hwcdn.libsyn.com/p/9/8/4/98404bf5b3ea8781/SM359.mp3?c_id=11311877&cs_id=11311877&expiration=1588266993&hwt=f45ec9fb46433bf14a8ac86ead82b7d2

**Comment by jshemas** [comment]
Hello, this should be fixed in the `4.0.0` version of this module.
