### ISSUE TITLE
Add Twitter Name Meta Tags Support

### ISSUE THREAD

**Issue by tavosansal** [jshemas/openGraphScraper#9]
Hello, 

This is not an issue necessarily but a feature request. I am wondering if it would be easy to add support for Twitter meta tags to show up in the scrape. I am trying to detect if a URL has twitter cards enabled (see: https://dev.twitter.com/cards/types/summary). I already use this library for scraping other open graph information and it would be extremely awesome if there was an option that you could set to opt in to get those Twitter values.

Thank you.

**Comment by jshemas** [comment]
Hey there,

This node modules is for scraping open graph data but it should be easy to update it to look for all those twitter tags too. I can probably look into this sometime this week.

**Comment by tavosansal** [comment]
That would amazing!
Thank you for your quick reply!

**Comment by jshemas** [comment]
Done. Please pull down the latest code. Let me know if you need anything else!

**Comment by tavosansal** [comment]
Awesome...thanks for the help!
