### ISSUE TITLE
Twitter scraping is not working

### ISSUE THREAD

**Issue by rynop** [jshemas/openGraphScraper#90]
Doesn't pull title, image etc.

Ex:
https://twitter.com/MarkRober/status/1256956499286298625

```javascript
{
  ogSiteName: 'Twitter',
  requestUrl: 'https://twitter.com/MarkRober/status/1256956499286298625',
  success: true
}
```

**Comment by jshemas** [comment]
Hello, I only see the `og:site_name` and `og:title` meta tags on that page. I'm not sure why `title` isn't being returned. I will look into this.

**Comment by jshemas** [comment]
It looks like you need JavaScript running in order for all of the meta tags to be there. You could use something like `puppeteer` to render the page with JavaScript running and then feed in the HTML into `openGraphScraper` using the `html` option.

**Comment by rynop** [comment]
Yea sorry I shoulda been more clear - you are exactly right, not sure why the `og:title` isn't returning.

https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-oembed is the open standard way to get embed HTML, but as you mention, it requires js execution.
