### ISSUE TITLE
Limited response

### ISSUE THREAD

**Issue by shih-js** [jshemas/openGraphScraper#99]
Using the latest version 4.3.1 and following the "usage example" returns limited results.

```
result: {
    requestUrl: 'http://ogp.me/',
    success: true
}
```

How do I get the og stuff?

**Comment by jshemas** [comment]
Hello,

Running:
```
const ogs = require('open-graph-scraper'); // using 4.3.1
const options = { url: 'http://ogp.me/' };
ogs(options, (error, results, response) => {
  console.log('error:', error); // This is returns true or false. True if there was a error. The error it self is inside the results object.
  console.log('results:', results); // This contains all of the Open Graph results
});
```
Returns this for me:
```
$ node app.js
error: false
results: {
  ogTitle: 'Open Graph protocol',
  ogType: 'website',
  ogUrl: 'http://ogp.me/',
  ogDescription: 'The Open Graph protocol enables any web page to become a rich object in a social graph.',
  ogImage: {
    url: 'http://ogp.me/logo.png',
    width: '300',
    height: '300',
    type: 'image/png'
  },
  requestUrl: 'http://ogp.me/',
  success: true
}
```

What version of node are you using? What OS are you using? Can you paste the output of `response` in here?

**Comment by shih-js** [comment]
**Node:** v14.0.0
**OS:** macOS Catalina 10.15.4

I'm thinking it may have something to do with the fact that I'm running this in a serverless function using the Next.js framework.

**Comment by jshemas** [comment]
Looks like there is something weird going on with node `v14.0.0`, but ogs works with node `v14.5.0`. Can you update?

**Comment by shih-js** [comment]
Got it working after updating node to 14.5.0.
Cheers!
